apiVersion: v1
kind: Config
preferences: {}

clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCVENDQWUyZ0F3SUJBZ0lJQmRyZnVRSmM2N2d3RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB5TlRFeU1qY3lNekF3TWpsYUZ3MHpOVEV5TWpVeU16QTFNamxhTUJVeApFekFSQmdOVkJBTVRDbXQxWW1WeWJtVjBaWE13Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLCkFvSUJBUURYR1dJRkFhVm1xOWFZUmsza0ptNUxucUlWdUs0elRpQ0Y4Nm5iZ0x2K2RGQ1pHczRmbkhxbWEyK0EKdTltdG5pcjZKU3BDeUY2NDVqcEQ0dllrTWlIS0lQYTZ0bG1PRFhBQTY3MTFLbUllVFNTL0UwWGpickNyTTBrdApzVVoxS2EzWnhBVTJtWHJxZGFTMUIrc3hnZ2luZXNJa1dpenQxUTlxbWltU0E3cEQwSTJneVJ6YkVzajBxM3JBCnRYRkNPM1lJcnlzM2dDdlNoWkxlMkw5Y3A3U2lWN011ZTYzd0drbWVaYkJnRHJ2V1ZSQUlvV3dmcWtqeUhNQnMKQ1F2cU5QZmd0TkM2eWZ3ZjlJUTlnOG5lcWIyNlZjdEgyZEpnZURvbUNGR0xrR1VpdjdSeDZtNkdNbTlaalA2dQptRDRlck15c3JWRm9BbkFNcE9XVGt3U3hhb3JGQWdNQkFBR2pXVEJYTUE0R0ExVWREd0VCL3dRRUF3SUNwREFQCkJnTlZIUk1CQWY4RUJUQURBUUgvTUIwR0ExVWREZ1FXQkJUNmgyNFJmOHZBbDlHVG1ZdkRxVlNsekNNc3lUQVYKQmdOVkhSRUVEakFNZ2dwcmRXSmxjbTVsZEdWek1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQTQ4RTE2dTdFRAp2VjlWZTZ4SGpDMEppMEh5NVJNWjY3eTFvaldyc2xXbm52OXBRV0xDS1JXUUZvbDNsY1h1K21MWDJhaWQ2djIyCjA4Y1FUQWZMTDhDVitBVloxMHg4bmhoNnhMTHU1ZEJMMlB3aGp2djNkdnFmSkkwalllVFFnQW5lU1JNUEZTdDUKMzN3MUNhalZaN1VENWtDWGlsUm5jRklYSFVCVGpSRkY3RmJ3QkluLzFENlhVL25CU09QaUhQRTVtMzVWaTRDMQpvVkgvenJPdlpZNERacTJjTkJDdGZlOU1YVGdKOFptcFlTUnYwTUc2Q0xrbExrOU9XYjRCRXcwVmN5NWIzRlovCi8vVkpvUDlWNVBJa01YcVZhNmFNNWFuMmxpbnYxZkt1NjVPeEw0NlRveVNrdEZFR3hOeERmSHBabDVtREplS0YKU3kzZGsybzV6dnBpCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://22deb032-0baf-4446-8910-7442578a6ecd.us-mia-2-gw.linodelke.net:443
  name: lke550142

users:
- name: lke550142-admin
  user:
    as-user-extra: {}
    token: eyJhbGciOiJSUzI1NiIsImtpZCI6ImhvTEJpR0w3S2d0alV6VXIyU0prVGZNTEJfS3REMTdiekludnE5bk5samcifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJrdWJlLXN5c3RlbSIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VjcmV0Lm5hbWUiOiJsa2UtYWRtaW4tdG9rZW4td3hxcjciLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC5uYW1lIjoibGtlLWFkbWluIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQudWlkIjoiNDE1NzM4MWItODU2OS00MWVlLWEwMmYtYWQwOGY2ODE1MDBiIiwic3ViIjoic3lzdGVtOnNlcnZpY2VhY2NvdW50Omt1YmUtc3lzdGVtOmxrZS1hZG1pbiJ9.SykqgJ1_894WqO_1IBe6e_Tw3Prli3tqQKKhJQApJrGtknKmhNGSh8-8f3YtGd1tA4NJ4rkk0AUuHJWXdQcB_W-Y8T5s_In6oNJVvEYqTjAcoFuNrACPZ_5kzKI2nsISMEee2loS9kIBq89YP4IIFf7aACdvx8bTFSNK8rf3iD5MNJWuRq81w1RpUmSEZhQxHd189zVxtaKNqwzt1VR0fWayuKOk1rYj5kSy9sVVsM9OflZmThLjYAOiQv35xgEtq6efJ4vy1Tpqm84ZXtggOAt4LN8gsjiwkgGoXXhtVZmoO8ddVHQQqr36c8aY6Y6jhKgcSfhEIwfBbRW5PXP4TQ

contexts:
- context:
    cluster: lke550142
    namespace: default
    user: lke550142-admin
  name: lke550142-ctx

current-context: lke550142-ctx
