apiVersion: apps/v1
kind: Deployment
metadata:
  name: networkchuckcoffee-deployment
  labels:
    app: nccoffee
spec:
  replicas: 20
  selector:
    matchLabels:
      app: nccoffee
  template:
    metadata:
      labels:
        app: nccoffee
    spec:
      containers:
      - name: static-site
        image: thenetworkchuck/nccoffee:vacpot
        imagePullPolicy: Always
        ports:
        - containerPort: 80

